on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name : install npm 
        run: npm install
      - name : change folder
        run: cd my-website
      - name : launch docusaurus
        run: npx docusaurus start
