on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
      - name : install npm
        run: npm install
      - name : launch docusaurus
        run: npx docusaurus start
